### ISSUE TITLE
Move data out of source code

### ISSUE THREAD

**Issue by Kenny2github** [getcake/EyeBleacherBot#1]
The strings in these two lines should both be loaded from files, so that they can be more easily configured.

https://github.com/getcake/EyeBleacherBot/blob/ca3a0455bed4545a5fe16017e66d5a3506dc359a/bot.py#L33

This message could just be loaded from a file like `footer.txt` or something - point is, you can edit it without worrying about string syntax.

https://github.com/getcake/EyeBleacherBot/blob/ca3a0455bed4545a5fe16017e66d5a3506dc359a/bot.py#L37

Example of what this could be changed to:
```python
# put this somewhere at the top level of bot.py
with open('watchedsubs.txt') as subs:
    subs = '+'.join(subs.read.splitlines())

# on line 37 of bot.py
for comment in reddit.subreddit(subs).stream.comments(skip_existing=True):
    ...
```
Then `watchedsubs.txt` could be
```
diwhy
ataae
cursedcursedcomments
casualuk
winstupidprizes
...
```

**Comment by getcake** [comment]
Awesome solution! This is much cleaner, I'm going to implement it now.
